### ISSUE TITLE
Align maven coordinates with JitPack

### ISSUE THREAD

**Issue by tdiesler** [multiformats/java-multiaddr#10]
Currently there is some confusion around groupId+artifactId and what jitpack is using. For maven builds, its important that these align.

JitPack releases like this

```
        <dependency>
            <groupId>com.github.multiformats</groupId>
            <artifactId>java-multiaddr</artifactId>
        </dependency>
```

which should also be the identity of the artifact in the pom. Alternatively, it may be possible to tweak JitPack to release with identity currently given in the pom.

**Comment by ianopolous** [comment]
I'm happy to accept a PR on this.

**Comment by tdiesler** [comment]
It's been sitting here: https://github.com/multiformats/java-multiaddr/pull/11
