### ISSUE TITLE
Feature Support /ip4/0.0.0.0/udp/4001/quic Addresses

### ISSUE THREAD

**Issue by remmerw** [multiformats/java-multiaddr#15]
Support /ip4/0.0.0.0/udp/4001/quic Addresses
Multiaddress has only a function getTCPPort() , maybe in this case also a general getPort() function
would be nice or (getTCPUDPPort())

**Comment by ianopolous** [comment]
Agreed, now that we have udp in multiaddrs a general getPort() is better.

**Comment by ianopolous** [comment]
I've added this in master now
