### ISSUE TITLE
question: why is java-multiaddr (and other java libraries) set to java 11, while no java11 features are used?

### ISSUE THREAD

**Issue by jhpoelen** [multiformats/java-multiaddr#22]
question: why is java-multiaddr (and other java libraries) set to java 11, while no java11 features are used?

**Comment by ianopolous** [comment]
Java 11 is just the default we use. It's quite old now.

**Comment by jhpoelen** [comment]
@ianopolous thanks for your prompt reply. 

Please note that (from https://github.com/globalbioticinteractions/nomer#prerequisites) - 

[Why OpenJDK 8?](https://adoptopenjdk.net/support.html). Because OpenJDK 8 is Long Term Supported (LTS), and (at time of writing Nov 2021) supported until at least May 2026, longer than any of the newer OpenJDK versions.

So, yes, java 8 is quite old, but it is supported long term, whereas newer java versions are not. 

Is newer always better?
